### ISSUE TITLE
Macでバックスラッシュを入れる方法

### ISSUE THREAD

**Issue by xtetsuji** [perl-entrance-org/workshop-2019#45]
perl-entrance-org/workshop-2014-01#4 からなのですが、2019年の資料はどうなっていたか、また最新OSではどのような状況か確認しておきたいです。

もしかしたらすでに解決されているかもしれませんが、その時はこの Issue をクローズします。

**Comment by sironekotoro** [comment]
現行テキストだとこんな感じです。

https://github.com/perl-entrance-org/workshop-2019/blob/master/1st/part3.md#hello-world-1
```
printは, 端末に文字を出力する命令です.
    \nは改行を意味します.
    Macの日本語キーボードの場合, \はOption + ￥キーで入力できます.
```

手元にあるMacが英語配列なので、日本語配列では表示違うかもしれませんが、以下のところに設定画面がありました(macOS Mojave 10.14.6 )

システム環境設定 -> キーボード -> 「入力ソース」タブ -> 「"￥"キーで表示する文字」

![image](https://user-images.githubusercontent.com/8675420/66250435-a82d9a80-e77d-11e9-81b0-968426f0c9d9.png)

**Comment by xtetsuji** [comment]
確かに、これ記載されていましたね！これでいったん大丈夫そうです。

とりあえず2014年の課題は5年のうちに自然に解決したということでクローズします！確認ありがとうございます！
